version: "3.7"

services:
  app:
    ports:
      - 8000:9000
    container_name: web
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    #   - ./packages/landingpage:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env